import Head from 'next/head'
import { Container } from 'react-bootstrap'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main>
          <Container>
            <h1 className="text-center">
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>
          </Container>
        </main>
      </body>
    </>
  )
}
